apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-deployment
spec:
  selector:
    matchLabels:
      app: message-service
  replicas: 2
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: message-service:latest
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 30
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: message
  labels:
    run: message-service
spec:
  ports:
  - port: 80
  selector:
    run: message-service