apiVersion: v1
kind: Pod
metadata:
  name: message-service
spec:
  containers:
  - name: message-service
    image: message-service:latest
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 15
    ports:
      - containerPort: 80


